param(
  [string[]]$TargetRepos = @(),
  [string]$ReposFile = "",
  [string]$BaseDir = "",
  [switch]$WithoutCopilotInstructions,
  [switch]$Force,
  [switch]$DryRun
)

# Purpose: Install guardrails-kit into multiple git repositories in one command.
# Usage:
#   pwsh -File scripts/install_many_repos.ps1 -BaseDir C:\repos -TargetRepos repo-a,repo-b
#   pwsh -File scripts/install_many_repos.ps1 -ReposFile .\repos.txt -Force
# Exit codes:
#   0 on full success, 1 if one or more repositories fail.

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$InstallScript = Join-Path $ScriptDir "install_into_repo.ps1"

if (-not (Test-Path $InstallScript -PathType Leaf)) {
  throw "Missing installer script: $InstallScript"
}

$repoInputs = New-Object System.Collections.Generic.List[string]
$successfulTargets = New-Object System.Collections.Generic.List[string]

foreach ($repo in $TargetRepos) {
  if (-not [string]::IsNullOrWhiteSpace($repo)) {
    $repoInputs.Add($repo.Trim())
  }
}

if (-not [string]::IsNullOrWhiteSpace($ReposFile)) {
  if (-not (Test-Path $ReposFile -PathType Leaf)) {
    throw "Repos file not found: $ReposFile"
  }

  Get-Content $ReposFile | ForEach-Object {
    $line = $_
    $commentIdx = $line.IndexOf("#")
    if ($commentIdx -ge 0) {
      $line = $line.Substring(0, $commentIdx)
    }
    $line = $line.Trim()
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      $repoInputs.Add($line)
    }
  }
}

if ($repoInputs.Count -eq 0) {
  throw "No repositories provided. Use -TargetRepos and/or -ReposFile."
}

function Resolve-RepoPath {
  param(
    [string]$InputRepo,
    [string]$BaseDirPath
  )

  if ([string]::IsNullOrWhiteSpace($BaseDirPath)) {
    return $InputRepo
  }

  if ([System.IO.Path]::IsPathRooted($InputRepo)) {
    return $InputRepo
  }

  return (Join-Path $BaseDirPath $InputRepo)
}

$success = 0
$failed = 0

foreach ($repo in $repoInputs) {
  $target = Resolve-RepoPath -InputRepo $repo -BaseDirPath $BaseDir
  Write-Host "---"
  Write-Host "Processing: $target"

  if ($DryRun.IsPresent) {
    $cmdPreview = "pwsh -File `"$InstallScript`" `"$target`""
    if ($WithoutCopilotInstructions.IsPresent) { $cmdPreview += " -WithoutCopilotInstructions" }
    if ($Force.IsPresent) { $cmdPreview += " -Force" }
    Write-Host "DRY RUN: $cmdPreview"
    $success++
    continue
  }

  try {
    $installParams = @{
      TargetRepo = $target
    }
    if ($WithoutCopilotInstructions.IsPresent) {
      $installParams["WithoutCopilotInstructions"] = $true
    }
    if ($Force.IsPresent) {
      $installParams["Force"] = $true
    }

    & $InstallScript @installParams
    $success++
    $successfulTargets.Add($target)
  }
  catch {
    Write-Host "FAILED: $target" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor DarkRed
    $failed++
  }
}

Write-Host "---"
Write-Host "Completed. Success: $success | Failed: $failed"

if ($success -gt 1) {
  $workspaceRoot = if ([string]::IsNullOrWhiteSpace($BaseDir)) { "." } else { $BaseDir }
  $agDir = Join-Path $workspaceRoot ".antigravity"
  New-Item -ItemType Directory -Force $agDir | Out-Null
  $agFile = Join-Path $agDir "workspace.yaml"
  
  $content = @(
    "# Antigravity IDE Multi-Repo Workspace"
    "# Auto-generated by install_many_repos.ps1"
    ""
    "project:"
    "  name: multi-repo-workspace"
    "  root: ."
    ""
    "workspace:"
    "  folders:"
  )
  
  foreach ($t in $successfulTargets) {
    $name = Split-Path -Leaf $t
    $content += "    - path: $t"
    $content += "      name: $name"
  }
  
  Set-Content -Path $agFile -Value $content
  Write-Host "✓ Generated multi-repo Antigravity workspace at $agFile" -ForegroundColor Green
}

if ($failed -gt 0) {
  exit 1
}
