#!/usr/bin/env bash
set -euo pipefail

# Purpose: Install guardrails-kit into multiple git repositories in one command.
# Usage:
#   bash scripts/install_many_repos.sh --base-dir /path/to/repos repo-a repo-b
#   bash scripts/install_many_repos.sh --repos-file repos.txt --force
# Arguments:
#   Positional repos      List of repository paths or names (when used with --base-dir).
#   --base-dir <dir>      Optional base directory for relative repository names.
#   --repos-file <file>   Optional file containing one repo path/name per line.
#   --without-copilot-instructions  Forwarded to install_into_repo.sh.
#   --force               Overwrite existing files in target repos.
#   --dry-run             Show what would be executed without applying changes.
# Exit codes:
#   0 on full success, 1 if one or more repositories fail.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_SCRIPT="${SCRIPT_DIR}/install_into_repo.sh"

if [[ ! -x "${INSTALL_SCRIPT}" ]]; then
  echo "Missing or non-executable installer: ${INSTALL_SCRIPT}" >&2
  exit 1
fi

BASE_DIR=""
REPOS_FILE=""
DRY_RUN=0
FORWARD_ARGS=()
REPO_INPUTS=()
SUCCESSFUL_TARGETS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-dir)
      BASE_DIR="${2:-}"
      if [[ -z "${BASE_DIR}" ]]; then
        echo "--base-dir requires a value" >&2
        exit 1
      fi
      shift 2
      ;;
    --repos-file)
      REPOS_FILE="${2:-}"
      if [[ -z "${REPOS_FILE}" ]]; then
        echo "--repos-file requires a value" >&2
        exit 1
      fi
      shift 2
      ;;
    --without-copilot-instructions|--force)
      FORWARD_ARGS+=("$1")
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      cat <<'EOF'
Usage: install_many_repos.sh [options] [repo ...]

Options:
  --base-dir <dir>      Base directory for relative repo names.
  --repos-file <file>   File containing one repo path/name per line.
  --without-copilot-instructions
                        Skip .github/copilot-instructions.md generation.
  --force               Overwrite existing guardrails files.
  --dry-run             Print actions without applying.
  -h, --help            Show this help.

Examples:
  bash scripts/install_many_repos.sh --base-dir /work/repos repo1 repo2
  bash scripts/install_many_repos.sh --repos-file repos.txt --force
EOF
      exit 0
      ;;
    --*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      REPO_INPUTS+=("$1")
      shift
      ;;
  esac
done

if [[ -n "${REPOS_FILE}" ]]; then
  if [[ ! -f "${REPOS_FILE}" ]]; then
    echo "Repos file not found: ${REPOS_FILE}" >&2
    exit 1
  fi
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [[ -z "$line" ]] && continue
    REPO_INPUTS+=("$line")
  done < "${REPOS_FILE}"
fi

if [[ ${#REPO_INPUTS[@]} -eq 0 ]]; then
  echo "No repositories provided. Use positional args or --repos-file." >&2
  exit 1
fi

resolve_repo_path() {
  local input="$1"
  if [[ -n "${BASE_DIR}" && "$input" != /* ]]; then
    echo "${BASE_DIR%/}/$input"
  else
    echo "$input"
  fi
}

SUCCESS=0
FAIL=0

for repo in "${REPO_INPUTS[@]}"; do
  target="$(resolve_repo_path "$repo")"
  echo "---"
  echo "Processing: ${target}"

  if [[ ${DRY_RUN} -eq 1 ]]; then
    echo "DRY RUN: bash ${INSTALL_SCRIPT} ${target} ${FORWARD_ARGS[*]}"
    SUCCESS=$((SUCCESS + 1))
    continue
  fi

  if bash "${INSTALL_SCRIPT}" "${target}" "${FORWARD_ARGS[@]}"; then
    SUCCESS=$((SUCCESS + 1))
    SUCCESSFUL_TARGETS+=("${target}")
  else
    echo "FAILED: ${target}" >&2
    FAIL=$((FAIL + 1))
  fi
done

echo "---"
echo "Completed. Success: ${SUCCESS} | Failed: ${FAIL}"

if [[ ${SUCCESS} -gt 1 ]]; then
  WORKSPACE_ROOT="${BASE_DIR:-.}"
  AG_DIR="${WORKSPACE_ROOT}/.antigravity"
  mkdir -p "${AG_DIR}"
  AG_FILE="${AG_DIR}/workspace.yaml"
  
  cat > "${AG_FILE}" <<EOF
# Antigravity IDE Multi-Repo Workspace
# Auto-generated by install_many_repos.sh

project:
  name: multi-repo-workspace
  root: .

workspace:
  folders:
EOF

  for target in "${SUCCESSFUL_TARGETS[@]}"; do
    name="$(basename "$target")"
    echo "    - path: ${target}" >> "${AG_FILE}"
    echo "      name: ${name}" >> "${AG_FILE}"
  done
  
  echo "✓ Generated multi-repo Antigravity workspace at ${AG_FILE}"
fi

if [[ ${FAIL} -gt 0 ]]; then
  exit 1
fi
